# DataSource Config
spring:
  datasource:
    name: dianping
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url:  jdbc:mysql://119.3.49.76:3307/library?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    type: com.alibaba.druid.pool.DruidDataSource
  resources:
    #true表示所有的controller都没有命中，则使用默认静态资源
    add-mappings: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static/**

mybatis-plus:
  type-aliases-package: landsky.library.entity
  global-config:
    db-config:
      logic-delete-field: flag  #全局逻辑删除字段值 3.3.0开始支持，详情看下面。
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

server:
  port: 9100

elasticsearch:
  ip: 121.36.170.246:9200
  ip1: 121.36.170.246:9200
  ip2: 121.36.170.246:9201
  ip3: 121.36.170.246:9202
